# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: '\.api$'
    -   id: end-of-file-fixer
        exclude: '\.api$'
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: api-check
        name: Gradle API compatibility check
        entry: ./gradlew apiCheck
        pass_filenames: false
        language: system
